package c19

import (
	"errors"
	"net/http"
	"strings"
)

var baseURL = "https://api.covid19api.com/"

var client = http.DefaultClient

var errStatus = errors.New("Invalid status. Status must be one of: confirmed, recovered, deaths")
var errCountry = errors.New("Invalid country")

var CountriesMap = map[string]struct{}{
	"kazakhstan":                      {},
	"saint kitts and nevis":           {},
	"saudi arabia":                    {},
	"uganda":                          {},
	"ukraine":                         {},
	"viet nam":                        {},
	"guam":                            {},
	"iraq":                            {},
	"northern mariana islands":        {},
	"san marino":                      {},
	"switzerland":                     {},
	"tajikistan":                      {},
	"congo (kinshasa)":                {},
	"comoros":                         {},
	"mauritania":                      {},
	"hungary":                         {},
	"swaziland":                       {},
	"cuba":                            {},
	"latvia":                          {},
	"united kingdom":                  {},
	"oman":                            {},
	"saint vincent and grenadines":    {},
	"falkland islands (malvinas)":     {},
	"saint lucia":                     {},
	"sierra leone":                    {},
	"lebanon":                         {},
	"portugal":                        {},
	"sri lanka":                       {},
	"estonia":                         {},
	"lithuania":                       {},
	"croatia":                         {},
	"myanmar":                         {},
	"nauru":                           {},
	"kenya":                           {},
	"romania":                         {},
	"tunisia":                         {},
	"chad":                            {},
	"dominica":                        {},
	"honduras":                        {},
	"montserrat":                      {},
	"zambia":                          {},
	"american samoa":                  {},
	"cocos (keeling) islands":         {},
	"uzbekistan":                      {},
	"antarctica":                      {},
	"dominican republic":              {},
	"niue":                            {},
	"palau":                           {},
	"botswana":                        {},
	"turks and caicos islands":        {},
	"wallis and futuna islands":       {},
	"bangladesh":                      {},
	"brazil":                          {},
	"central african republic":        {},
	"norfolk island":                  {},
	"saint-barthélemy":                {},
	"vanuatu":                         {},
	"congo (brazzaville)":             {},
	"guadeloupe":                      {},
	"italy":                           {},
	"brunei darussalam":               {},
	"denmark":                         {},
	"ecuador":                         {},
	"el salvador":                     {},
	"holy see (vatican city state)":   {},
	"somalia":                         {},
	"angola":                          {},
	"fiji":                            {},
	"united states of america":        {},
	"mauritius":                       {},
	"benin":                           {},
	"french polynesia":                {},
	"greenland":                       {},
	"india":                           {},
	"kiribati":                        {},
	"cyprus":                          {},
	"iceland":                         {},
	"saint pierre and miquelon":       {},
	"jordan":                          {},
	"slovenia":                        {},
	"bahrain":                         {},
	"hong kong, sar china":            {},
	"czech republic":                  {},
	"guatemala":                       {},
	"madagascar":                      {},
	"moldova":                         {},
	"paraguay":                        {},
	"austria":                         {},
	"british virgin islands":          {},
	"costa rica":                      {},
	"gabon":                           {},
	"mayotte":                         {},
	"micronesia, federated states of": {},
	"netherlands antilles":            {},
	"new caledonia":                   {},
	"niger":                           {},
	"trinidad and tobago":             {},
	"australia":                       {},
	"korea (south)":                   {},
	"namibia":                         {},
	"pakistan":                        {},
	"korea (north)":                   {},
	"luxembourg":                      {},
	"zimbabwe":                        {},
	"qatar":                           {},
	"china":                           {},
	"egypt":                           {},
	"ireland":                         {},
	"mozambique":                      {},
	"netherlands":                     {},
	"cambodia":                        {},
	"gambia":                          {},
	"papua new guinea":                {},
	"puerto rico":                     {},
	"bermuda":                         {},
	"bhutan":                          {},
	"indonesia":                       {},
	"taiwan, republic of china":       {},
	"turkmenistan":                    {},
	"burkina faso":                    {},
	"malaysia":                        {},
	"mongolia":                        {},
	"south sudan":                     {},
	"spain":                           {},
	"bolivia":                         {},
	"guyana":                          {},
	"cayman islands":                  {},
	"georgia":                         {},
	"solomon islands":                 {},
	"republic of kosovo":              {},
	"togo":                            {},
	"liechtenstein":                   {},
	"montenegro":                      {},
	"saint helena":                    {},
	"samoa":                           {},
	"virgin islands, us":              {},
	"venezuela (bolivarian republic)": {},
	"azerbaijan":                      {},
	"cameroon":                        {},
	"ala aland islands":               {},
	"malta":                           {},
	"panama":                          {},
	"uruguay":                         {},
	"albania":                         {},
	"equatorial guinea":               {},
	"israel":                          {},
	"malawi":                          {},
	"bosnia and herzegovina":          {},
	"cape verde":                      {},
	"liberia":                         {},
	"nepal":                           {},
	"british indian ocean territory":  {},
	"french guiana":                   {},
	"us minor outlying islands":       {},
	"western sahara":                  {},
	"algeria":                         {},
	"bouvet island":                   {},
	"guinea":                          {},
	"iran, islamic republic of":       {},
	"senegal":                         {},
	"suriname":                        {},
	"eritrea":                         {},
	"ethiopia":                        {},
	"jamaica":                         {},
	"mexico":                          {},
	"philippines":                     {},
	"réunion":                         {},
	"barbados":                        {},
	"nicaragua":                       {},
	"nigeria":                         {},
	"seychelles":                      {},
	"south georgia and the south sandwich islands": {},
	"jersey":                         {},
	"mali":                           {},
	"morocco":                        {},
	"united arab emirates":           {},
	"macao, sar china":               {},
	"peru":                           {},
	"colombia":                       {},
	"monaco":                         {},
	"pitcairn":                       {},
	"poland":                         {},
	"sweden":                         {},
	"kyrgyzstan":                     {},
	"serbia":                         {},
	"armenia":                        {},
	"belize":                         {},
	"canada":                         {},
	"ghana":                          {},
	"guinea-bissau":                  {},
	"lesotho":                        {},
	"maldives":                       {},
	"afghanistan":                    {},
	"argentina":                      {},
	"belgium":                        {},
	"burundi":                        {},
	"isle of man":                    {},
	"palestinian territory":          {},
	"cook islands":                   {},
	"french southern territories":    {},
	"russian federation":             {},
	"turkey":                         {},
	"antigua and barbuda":            {},
	"faroe islands":                  {},
	"japan":                          {},
	"sudan":                          {},
	"timor-leste":                    {},
	"chile":                          {},
	"côte d'ivoire":                  {},
	"libya":                          {},
	"macedonia, republic of":         {},
	"singapore":                      {},
	"djibouti":                       {},
	"heard and mcdonald islands":     {},
	"tuvalu":                         {},
	"bahamas":                        {},
	"haiti":                          {},
	"saint-martin (french part)":     {},
	"south africa":                   {},
	"yemen":                          {},
	"finland":                        {},
	"guernsey":                       {},
	"lao pdr":                        {},
	"aruba":                          {},
	"belarus":                        {},
	"norway":                         {},
	"rwanda":                         {},
	"christmas island":               {},
	"gibraltar":                      {},
	"grenada":                        {},
	"syrian arab republic (syria)":   {},
	"tonga":                          {},
	"andorra":                        {},
	"bulgaria":                       {},
	"france":                         {},
	"martinique":                     {},
	"tanzania, united republic of":   {},
	"anguilla":                       {},
	"sao tome and principe":          {},
	"thailand":                       {},
	"greece":                         {},
	"marshall islands":               {},
	"svalbard and jan mayen islands": {},
	"tokelau":                        {},
	"germany":                        {},
	"kuwait":                         {},
	"new zealand":                    {},
	"slovakia":                       {},
}

func IsValidCountry(country string) bool {
	if _, ok := CountriesMap[strings.ToLower(country)]; ok {
		return true
	}
	return false
}
