package c19

import (
	"errors"
	"net/http"
	"strings"
)

var baseURL = "https://api.covid19api.com"

type Client struct {
	client  *http.Client
	BaseURL string
}

//NewClient returns new Client
func NewClient() *Client {
	return &Client{
		client:  http.DefaultClient,
		BaseURL: baseURL,
	}
}

var errStatus = errors.New("Invalid status. Status must be one of: confirmed, recovered, deaths")
var errCountry = errors.New("Invalid country")

func isAvailableStatus(status string) bool {
	if status == "confirmed" || status == "recovered" || status == "deaths" {
		return true
	}
	return false
}

//IsValidCountry check what this country valid or not
func IsValidCountry(country string) bool {
	if _, ok := CountriesMap[strings.ToLower(country)]; ok {
		return true
	}
	if _, ok := CountriesMapSlag[strings.ToLower(country)]; ok {
		return true
	}
	return false
}

//CountriesMap is a map that contains all countries in slug form
var CountriesMap = map[string]struct{}{
	"kazakhstan":                      {},
	"saint kitts and nevis":           {},
	"saudi arabia":                    {},
	"uganda":                          {},
	"ukraine":                         {},
	"viet nam":                        {},
	"guam":                            {},
	"iraq":                            {},
	"northern mariana islands":        {},
	"san marino":                      {},
	"switzerland":                     {},
	"tajikistan":                      {},
	"congo (kinshasa)":                {},
	"comoros":                         {},
	"mauritania":                      {},
	"hungary":                         {},
	"swaziland":                       {},
	"cuba":                            {},
	"latvia":                          {},
	"united kingdom":                  {},
	"oman":                            {},
	"saint vincent and grenadines":    {},
	"falkland islands (malvinas)":     {},
	"saint lucia":                     {},
	"sierra leone":                    {},
	"lebanon":                         {},
	"portugal":                        {},
	"sri lanka":                       {},
	"estonia":                         {},
	"lithuania":                       {},
	"croatia":                         {},
	"myanmar":                         {},
	"nauru":                           {},
	"kenya":                           {},
	"romania":                         {},
	"tunisia":                         {},
	"chad":                            {},
	"dominica":                        {},
	"honduras":                        {},
	"montserrat":                      {},
	"zambia":                          {},
	"american samoa":                  {},
	"cocos (keeling) islands":         {},
	"uzbekistan":                      {},
	"antarctica":                      {},
	"dominican republic":              {},
	"niue":                            {},
	"palau":                           {},
	"botswana":                        {},
	"turks and caicos islands":        {},
	"wallis and futuna islands":       {},
	"bangladesh":                      {},
	"brazil":                          {},
	"central african republic":        {},
	"norfolk island":                  {},
	"saint-barthélemy":                {},
	"vanuatu":                         {},
	"congo (brazzaville)":             {},
	"guadeloupe":                      {},
	"italy":                           {},
	"brunei darussalam":               {},
	"denmark":                         {},
	"ecuador":                         {},
	"el salvador":                     {},
	"holy see (vatican city state)":   {},
	"somalia":                         {},
	"angola":                          {},
	"fiji":                            {},
	"united states of america":        {},
	"mauritius":                       {},
	"benin":                           {},
	"french polynesia":                {},
	"greenland":                       {},
	"india":                           {},
	"kiribati":                        {},
	"cyprus":                          {},
	"iceland":                         {},
	"saint pierre and miquelon":       {},
	"jordan":                          {},
	"slovenia":                        {},
	"bahrain":                         {},
	"hong kong, sar china":            {},
	"czech republic":                  {},
	"guatemala":                       {},
	"madagascar":                      {},
	"moldova":                         {},
	"paraguay":                        {},
	"austria":                         {},
	"british virgin islands":          {},
	"costa rica":                      {},
	"gabon":                           {},
	"mayotte":                         {},
	"micronesia, federated states of": {},
	"netherlands antilles":            {},
	"new caledonia":                   {},
	"niger":                           {},
	"trinidad and tobago":             {},
	"australia":                       {},
	"korea (south)":                   {},
	"namibia":                         {},
	"pakistan":                        {},
	"korea (north)":                   {},
	"luxembourg":                      {},
	"zimbabwe":                        {},
	"qatar":                           {},
	"china":                           {},
	"egypt":                           {},
	"ireland":                         {},
	"mozambique":                      {},
	"netherlands":                     {},
	"cambodia":                        {},
	"gambia":                          {},
	"papua new guinea":                {},
	"puerto rico":                     {},
	"bermuda":                         {},
	"bhutan":                          {},
	"indonesia":                       {},
	"taiwan, republic of china":       {},
	"turkmenistan":                    {},
	"burkina faso":                    {},
	"malaysia":                        {},
	"mongolia":                        {},
	"south sudan":                     {},
	"spain":                           {},
	"bolivia":                         {},
	"guyana":                          {},
	"cayman islands":                  {},
	"georgia":                         {},
	"solomon islands":                 {},
	"republic of kosovo":              {},
	"togo":                            {},
	"liechtenstein":                   {},
	"montenegro":                      {},
	"saint helena":                    {},
	"samoa":                           {},
	"virgin islands, us":              {},
	"venezuela (bolivarian republic)": {},
	"azerbaijan":                      {},
	"cameroon":                        {},
	"ala aland islands":               {},
	"malta":                           {},
	"panama":                          {},
	"uruguay":                         {},
	"albania":                         {},
	"equatorial guinea":               {},
	"israel":                          {},
	"malawi":                          {},
	"bosnia and herzegovina":          {},
	"cape verde":                      {},
	"liberia":                         {},
	"nepal":                           {},
	"british indian ocean territory":  {},
	"french guiana":                   {},
	"us minor outlying islands":       {},
	"western sahara":                  {},
	"algeria":                         {},
	"bouvet island":                   {},
	"guinea":                          {},
	"iran, islamic republic of":       {},
	"senegal":                         {},
	"suriname":                        {},
	"eritrea":                         {},
	"ethiopia":                        {},
	"jamaica":                         {},
	"mexico":                          {},
	"philippines":                     {},
	"réunion":                         {},
	"barbados":                        {},
	"nicaragua":                       {},
	"nigeria":                         {},
	"seychelles":                      {},
	"south georgia and the south sandwich islands": {},
	"jersey":                         {},
	"mali":                           {},
	"morocco":                        {},
	"united arab emirates":           {},
	"macao, sar china":               {},
	"peru":                           {},
	"colombia":                       {},
	"monaco":                         {},
	"pitcairn":                       {},
	"poland":                         {},
	"sweden":                         {},
	"kyrgyzstan":                     {},
	"serbia":                         {},
	"armenia":                        {},
	"belize":                         {},
	"canada":                         {},
	"ghana":                          {},
	"guinea-bissau":                  {},
	"lesotho":                        {},
	"maldives":                       {},
	"afghanistan":                    {},
	"argentina":                      {},
	"belgium":                        {},
	"burundi":                        {},
	"isle of man":                    {},
	"palestinian territory":          {},
	"cook islands":                   {},
	"french southern territories":    {},
	"russian federation":             {},
	"turkey":                         {},
	"antigua and barbuda":            {},
	"faroe islands":                  {},
	"japan":                          {},
	"sudan":                          {},
	"timor-leste":                    {},
	"chile":                          {},
	"côte d'ivoire":                  {},
	"libya":                          {},
	"macedonia, republic of":         {},
	"singapore":                      {},
	"djibouti":                       {},
	"heard and mcdonald islands":     {},
	"tuvalu":                         {},
	"bahamas":                        {},
	"haiti":                          {},
	"saint-martin (french part)":     {},
	"south africa":                   {},
	"yemen":                          {},
	"finland":                        {},
	"guernsey":                       {},
	"lao pdr":                        {},
	"aruba":                          {},
	"belarus":                        {},
	"norway":                         {},
	"rwanda":                         {},
	"christmas island":               {},
	"gibraltar":                      {},
	"grenada":                        {},
	"syrian arab republic (syria)":   {},
	"tonga":                          {},
	"andorra":                        {},
	"bulgaria":                       {},
	"france":                         {},
	"martinique":                     {},
	"tanzania, united republic of":   {},
	"anguilla":                       {},
	"sao tome and principe":          {},
	"thailand":                       {},
	"greece":                         {},
	"marshall islands":               {},
	"svalbard and jan mayen islands": {},
	"tokelau":                        {},
	"germany":                        {},
	"kuwait":                         {},
	"new zealand":                    {},
	"slovakia":                       {},
}

//CountriesMapSlag is a map that contains all countries in slug form
var CountriesMapSlag = map[string]struct{}{
	"british-virgin-islands":         {},
	"china":                          {},
	"kosovo":                         {},
	"dominican-republic":             {},
	"saudi-arabia":                   {},
	"italy":                          {},
	"niue":                           {},
	"algeria":                        {},
	"belize":                         {},
	"comoros":                        {},
	"haiti":                          {},
	"belgium":                        {},
	"mali":                           {},
	"french-polynesia":               {},
	"cook-islands":                   {},
	"bermuda":                        {},
	"ghana":                          {},
	"guinea":                         {},
	"tajikistan":                     {},
	"luxembourg":                     {},
	"sudan":                          {},
	"swaziland":                      {},
	"san-marino":                     {},
	"barbados":                       {},
	"estonia":                        {},
	"australia":                      {},
	"greece":                         {},
	"tokelau":                        {},
	"czech-republic":                 {},
	"nigeria":                        {},
	"martinique":                     {},
	"poland":                         {},
	"wallis-and-futuna-islands":      {},
	"ecuador":                        {},
	"guinea-bissau":                  {},
	"senega":                         {},
	"montenegro":                     {},
	"new-caledonia":                  {},
	"antigua-and-barbud":             {},
	"brunei":                         {},
	"honduras":                       {},
	"libya":                          {},
	"switzerland":                    {},
	"us-minor-outlying-islands":      {},
	"azerbaijan":                     {},
	"costa-rica":                     {},
	"egypt":                          {},
	"lao-pdr":                        {},
	"venezuela":                      {},
	"austria":                        {},
	"fiji":                           {},
	"jordan":                         {},
	"saint-kitts-and-nevis":          {},
	"slovakia":                       {},
	"turkey":                         {},
	"falkland-islands-malvinas":      {},
	"kenya":                          {},
	"micronesia":                     {},
	"latvia":                         {},
	"andorra":                        {},
	"anguilla":                       {},
	"el-salvador":                    {},
	"iran":                           {},
	"burundi":                        {},
	"saint-barthélemy":               {},
	"seychelles":                     {},
	"palau":                          {},
	"panama":                         {},
	"grenada":                        {},
	"uzbekistan":                     {},
	"bosnia-and-herzegovina":         {},
	"vietnam":                        {},
	"jersey":                         {},
	"bhutan":                         {},
	"british-indian-ocean-territory": {},
	"cuba":                           {},
	"isle-of-man":                    {},
	"ethiopia":                       {},
	"virgin-islands":                 {},
	"hungary":                        {},
	"iceland":                        {},
	"india":                          {},
	"tuvalu":                         {},
	"argentina":                      {},
	"cyprus":                         {},
	"gambia":                         {},
	"holy-see-vatican-city-state":    {},
	"united-states":                  {},
	"cote-divoire":                   {},
	"montserrat":                     {},
	"sierra-leone":                   {},
	"south-africa":                   {},
	"south-georgia-and-the-south-sandwich-islands": {},
	"syria":                            {},
	"cambodia":                         {},
	"saint-martin-french-part":         {},
	"mauritania":                       {},
	"palestine":                        {},
	"macao-sar-china":                  {},
	"nepal":                            {},
	"south-sudan":                      {},
	"tanzania":                         {},
	"aruba":                            {},
	"christmas-island":                 {},
	"eritrea":                          {},
	"kiribati":                         {},
	"united-kingdom":                   {},
	"bahamas":                          {},
	"chile":                            {},
	"namibia":                          {},
	"netherlands-antilles":             {},
	"norway":                           {},
	"réunion":                          {},
	"finland":                          {},
	"japan":                            {},
	"mauritius":                        {},
	"netherlands":                      {},
	"togo":                             {},
	"zimbabwe":                         {},
	"bulgaria":                         {},
	"french-southern-territories":      {},
	"madagascar":                       {},
	"lebanon":                          {},
	"rwanda":                           {},
	"slovenia":                         {},
	"suriname":                         {},
	"turks-and-caicos-islands":         {},
	"indonesia":                        {},
	"lithuania":                        {},
	"mayotte":                          {},
	"spain":                            {},
	"malaysia":                         {},
	"mozambique":                       {},
	"angola":                           {},
	"chad":                             {},
	"denmark":                          {},
	"faroe-islands":                    {},
	"georgia":                          {},
	"kazakhstan":                       {},
	"korea-south":                      {},
	"papua-new-guinea":                 {},
	"central-african-republic":         {},
	"france":                           {},
	"saint-pierre-and-miquelon":        {},
	"svalbard-and-jan-mayen-islands":   {},
	"sweden":                           {},
	"western-sahara":                   {},
	"iraq":                             {},
	"saint-lucia":                      {},
	"ukraine":                          {},
	"brazil":                           {},
	"pitcairn":                         {},
	"sao-tome-and-principe":            {},
	"congo-brazzaville":                {},
	"djibouti":                         {},
	"liechtenstein":                    {},
	"ala-aland-islands":                {},
	"colombia":                         {},
	"norfolk-island":                   {},
	"cayman-islands":                   {},
	"macedonia":                        {},
	"saint-helena":                     {},
	"bolivia":                          {},
	"burkina-faso":                     {},
	"canada":                           {},
	"ireland":                          {},
	"timor-leste":                      {},
	"albania":                          {},
	"bahrain":                          {},
	"guam":                             {},
	"heard-and-mcdonald-islands":       {},
	"new-zealand":                      {},
	"uruguay":                          {},
	"vanuatu":                          {},
	"zambia":                           {},
	"germany":                          {},
	"monaco":                           {},
	"portugal":                         {},
	"uganda":                           {},
	"israel":                           {},
	"peru":                             {},
	"nauru":                            {},
	"somalia":                          {},
	"greenland":                        {},
	"mexico":                           {},
	"moldova":                          {},
	"belarus":                          {},
	"cameroon":                         {},
	"gabon":                            {},
	"mongolia":                         {},
	"yemen":                            {},
	"antarctica":                       {},
	"cocos-keeling-islands":            {},
	"guadeloupe":                       {},
	"serbia":                           {},
	"thailand":                         {},
	"croatia":                          {},
	"guernsey":                         {},
	"russia":                           {},
	"guyana":                           {},
	"kuwait":                           {},
	"tunisia":                          {},
	"turkmenistan":                     {},
	"northern-mariana-islands":         {},
	"oman":                             {},
	"philippines":                      {},
	"botswana":                         {},
	"trinidad-and-tobago":              {},
	"myanmar":                          {},
	"nicaragua":                        {},
	"taiwan":                           {},
	"armenia":                          {},
	"solomon-islands":                  {},
	"liberia":                          {},
	"maldives":                         {},
	"niger":                            {},
	"bangladesh":                       {},
	"hong-kong-sar-china":              {},
	"jamaica":                          {},
	"lesotho":                          {},
	"guatemala":                        {},
	"kyrgyzstan":                       {},
	"malta":                            {},
	"marshall-islands":                 {},
	"morocco":                          {},
	"qatar":                            {},
	"cape-verde":                       {},
	"korea-north":                      {},
	"saint-vincent-and-the-grenadines": {},
	"sri-lanka":                        {},
	"united-arab-emirates":             {},
	"pakistan":                         {},
	"paraguay":                         {},
	"tonga":                            {},
	"bouvet-island":                    {},
	"dominica":                         {},
	"gibraltar":                        {},
	"samoa":                            {},
	"benin":                            {},
	"equatorial-guinea":                {},
	"malawi":                           {},
	"afghanistan":                      {},
	"american-samoa":                   {},
	"singapore":                        {},
	"congo-kinshasa":                   {},
	"romania":                          {},
	"french-guiana":                    {},
	"puerto-rico":                      {},
}
